invenio_gitlab/views/gitlab.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 HZDR
#
# This file is part of RODARE.
#
# invenio-gitlab is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# invenio-gitlab is distributed in the hope that
# it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rodare. If not, see <http://www.gnu.org/licenses/>.

"""GitLab settings blueprint for Invenio."""

from __future__ import absolute_import

import fnmatch
import json
from datetime import datetime

import humanize
import pytz
from dateutil.parser import parse
from flask import Blueprint, abort, current_app, render_template, request
from flask_babelex import gettext as _
from flask_breadcrumbs import register_breadcrumb
from flask_login import current_user, login_required
from flask_menu import register_menu
from invenio_db import db
from sqlalchemy.orm.exc import NoResultFound

from ..api import GitLabAPI, GitLabRelease
from ..errors import ProjectAccessError
from ..models import Project, Release
from ..proxies import current_gitlab
from ..utils import parse_timestamp, utcnow

blueprint = Blueprint(
    'invenio_gitlab',
    __name__,
    static_folder='../static',
    template_folder='../templates',
    url_prefix='/account/settings/gitlab',
)


#
# Template filters
#
@blueprint.app_template_filter('naturaltime')
def naturaltime(val):
    """Get humanized version of time."""
    val = val.replace(tzinfo=pytz.utc) \
        if isinstance(val, datetime) else parse(val)
    now = datetime.utcnow().replace(tzinfo=pytz.utc)

    return humanize.naturaltime(now - val)


@blueprint.app_template_filter('prettyjson')
def prettyjson(val):
    """Get pretty-printed json."""
    return json.dumps(json.loads(val), indent=4)


@blueprint.app_template_filter('release_pid')
def release_pid(release):
    """Get PID of Release record."""
    return GitLabRelease(release).pid


#
# Views
#
@blueprint.route('/', methods=['GET', 'POST'])
@login_required
@register_menu(
    blueprint, 'settings.gitlab',
    '<i class="fa fa-gitlab fa-fw"></i> GitLab',
    order=10,
    active_when=lambda: request.endpoint.startswith('invenio_gitlab.')
)
@register_breadcrumb(blueprint, 'breadcrumbs.settings.gitlab', _('GitLab'))
def index():
    """Display a list of user projects."""
    gitlab = GitLabAPI(user_id=current_user.id)
    token = gitlab.session_token
    ctx = dict(connected=False)
    if token:
        # We know, the token is still valid and the user is authenticated
        if gitlab.account.extra_data.get('login') is None:
            gitlab.init_account()
            db.session.commit()

        if request.method == 'POST' or gitlab.check_sync():
            # When we're in an XHR request, synchronously sync hooks
            gitlab.sync(async_hooks=(not request.is_xhr))
            db.session.commit()

        # Generate the projects view object
        extra_data = gitlab.account.extra_data
        projects = extra_data['projects']
        if projects:
            # Enhance the projects dict, from the database model.
            db_projects = Project.query.filter(
                Project.gitlab_id.in_([int(k) for k in projects.keys()]),
            ).all()
            for project in db_projects:
                projects[str(project.gitlab_id)]['instance'] = project
                projects[str(project.gitlab_id)]['latest'] = GitLabRelease(
                    project.latest_release())

        last_sync = humanize.naturaltime(
            (utcnow() - parse_timestamp(extra_data['last_sync'])))

        ctx.update({
            'connected': True,
            'projects': sorted(projects.items(),
                               key=lambda x: x[1]['full_name']),
            'last_sync': last_sync,
        })
    return render_template(current_app.config['GITLAB_TEMPLATE_INDEX'], **ctx)


@blueprint.route('/project/<path:name>')
@login_required
@register_breadcrumb(blueprint, 'breadcrumbs.settings.gitlab.project',
                     _('Project'))
def project(name):
    """Display selected project."""
    user_id = current_user.id
    gitlab = GitLabAPI(user_id=user_id)
    token = gitlab.session_token
    if token:
        projects = gitlab.account.extra_data.get('projects', [])
        project = next((project for project_id, project in projects.items()
                        if project.get('full_name') == name), {})
        if not project:
            abort(403)

        try:
            project_instance = Project.get(user_id=user_id,
                                           gitlab_id=project['id'],
                                           check_owner=False)
        except ProjectAccessError:
            abort(403)
        except NoResultFound:
            project_instance = Project(name=project['full_name'],
                                       gitlab_id=project['id'])
        releases = [
            current_gitlab.release_api_class(r) for r in (
                project_instance.releases.order_by(
                    db.desc(Release.created)).all()
                if project_instance.id else []
            )
        ]
        return render_template(
            current_app.config['GITLAB_TEMPLATE_VIEW'],
            project=project_instance,
            releases=releases,
            serializer=current_gitlab.record_serializer,
        )
    abort(403)


@blueprint.route('/hook', methods=['POST', 'DELETE'])
@login_required
def hook():
    """Install or delete GitLab webhook."""
    project_id = request.json['id']

    gitlab = GitLabAPI(user_id=current_user.id)
    projects = gitlab.account.extra_data['projects']

    if project_id not in projects:
        abort(404)

    if request.method == 'DELETE':
        try:
            if gitlab.remove_hook(project_id,
                                  projects[project_id]['full_name']):
                db.session.commit()
                return '', 204
            else:
                abort(400)
        except Exception:
            abort(403)
    elif request.method == 'POST':
        try:
            if gitlab.create_hook(project_id,
                                  projects[project_id]['full_name']):
                db.session.commit()
                return '', 201
            else:
                abort(400)
        except Exception:
            abort(403)
    else:
        abort(400)


@blueprint.route('/pattern', methods=['POST', 'DELETE'])
@login_required
def pattern():
    """Change the pattern used for release detection."""
    project_id = request.json.get('id', None)
    if not project_id:
        abort(400, _('Specify the project ID.'))

    try:
        project_instance = Project.get(user_id=current_user.id,
                                       gitlab_id=project_id,
                                       check_owner=True)
    except NoResultFound:
        abort(403)

    if request.method == 'POST':
        pattern = request.json.get('pattern', None)
        if not pattern:
            abort(400, _('Specify a valid glob pattern '
                         'for your releases.'))

        project_instance.release_pattern = pattern
        db.session.commit()
        return '', 204
    elif request.method == 'DELETE':
        # Reset pattern to the default value.
        project_instance.release_pattern = 'v*'
        db.session.commit()
        return '', 204

invenio_gitlab/templates/invenio_gitlab/settings/base.html
{%- extends "invenio_gitlab/base.html" %}

{%- block page_body %}
{%- block settings_content %}
{%- block settings_body %}
{%- block settings_form %}{%- endblock settings_form %}
{%- endblock settings_body %}
{%- endblock settings_content %}
{%- endblock page_body %}

invenio_gitlab/templates/invenio_gitlab/settings/helpers.html
{%- macro panel_start(title, icon="", btn_text='', btn='', btn_icon='',
                      btn_href='', btn_class='btn-default', btn_name='',
                      btn2='', btn_icon2='', btn_href2='', btn_class2='btn-default',
                      btn_name2='', id="", with_body=True, panel_extra_class="panel-default") %}
{%- block panel_start scoped %}
<div class="panel-group panel-bot-margin"{% if id %} id="{{id}}"{% endif %}>
    <div class="panel {{panel_extra_class}}">
        {%- block panel_heading scoped %}
        <div class="panel-heading">
            <strong>{%if icon %}<i class="{{icon}}"></i>{% endif %} {{title}}</strong>
            {%- if btn and (btn_href or btn_text) -%}
            <div class="pull-right" style="margin-left: 5px;">
            {%- if btn_text %}
                <small class="text-muted" style="padding-right: 10px;">(updated {{last_sync}})</small>
            {%- endif %}
            {%- if btn_href %}
            <a class="pull-right btn btn-xs {{btn_class}}" href="{{btn_href}}">{% if btn_icon %}<i class="{{btn_icon}}"></i> {% endif %}{{btn}}</a>
            {%- else %}
            {%- if btn_name %}
            <button name="{{btn_name}}" class="btn btn-xs {{btn_class}}">{% if btn_icon %}<i class="{{btn_icon}}"></i> {% endif %}{{btn}}</button>
            {%- endif %}
            {%- endif %}
            </div>
            {%- endif -%}
            {%- if btn2 and btn_href2 -%}
            <div class="pull-right" style="margin-left: 5px;">
            {%- if btn_href2 %}
            <a class="pull-right btn btn-xs {{btn_class2}}" href="{{btn_href2}}">{% if btn_icon2 %}<i class="{{btn_icon2}}"></i> {% endif %}{{btn2}}</a>
            {%- else %}
            {%- if btn_name2 %}
            <button name="{{btn_name2}}" class="btn btn-xs {{btn_class2}}">{% if btn_icon2 %}<i class="{{btn_icon2}}"></i> {% endif %}{{btn2}}</button>
            {%- endif %}
            {%- endif %}
            </div>
            {%- endif -%}
        </div>
        {%- endblock %}
        {%- if with_body %}
        <div class="panel-body">
        {%- endif %}
{%- endblock %}
{%- endmacro %}


{%- macro panel_end(with_body=True) %}
{%- block panel_end scoped %}
        {%- if with_body %}
        </div>
        {%- endif %}
    </div>
</div>
{%- endblock %}
{%- endmacro %}

{%- macro repo_switch(project, project_id, size='mini') %}
{%- block repo_switch scoped %}
  <i class="hook-status fa" data-repo-id="{{project_id}}"></i>
  {%- set inaccessible = (project and project.user_id and (project.user_id != current_user.id)) %}
  <span{%- if inaccessible %} data-toggle="tooltip" data-placement="top" title="{{_('This project is managed by another user in your GitLab instance.')}}"{%- endif %}>
  <input type="checkbox"{{' disabled' if inaccessible}}{{ ' checked' if project and project.enabled }} data-size="{{size}}" data-animate="true" data-repo-id="{{project_id}}">
  </span>
{%- endblock %}
{%- endmacro %}

invenio_gitlab/templates/invenio_gitlab/settings/index.html
{%- import "invenio_gitlab/settings/helpers.html" as helpers with context %}

{%- if not request.is_xhr %}
{%- extends config.GITLAB_SETTINGS_TEMPLATE %}

{%- block css %}
{{ super() }}
{% assets "invenio_gitlab_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{%- endblock css %}

{%- block javascript %}
{{ super() }}
{% assets "invenio_gitlab_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
<script type="text/javascript">
require(['jquery', 'js/gitlab/view'], function($, view) {
  $(document).ready(function(){
    view({
      hook_url: "{{url_for('invenio_gitlab.hook')}}",
      sync_url: "{{url_for('invenio_gitlab.index')}}",
      sync_button: "button[name='sync-repos']",
      gitlab_view: ".gitlab-panels"
    });
  });
});
</script>
{%- endblock %}
{%- endif %}

{%- block settings_content %}
<div class="gitlab-panels">
{%- if connected %}
{{ helpers.panel_start(
  _('GitLab Projects'),
  with_body=False,
  icon="fa fa-gitlab",
  btn='Sync now ...',
  btn_icon='fa fa-refresh',
  btn_name='sync-repos',
  btn_text=_('(updated %(last_sync)s) ', last_sync=last_sync),
  id="gitlab-view",
) }}
<div class="panel-body">
  <h1 align="center"><i class="fa fa-gitlab"></i> Get started</h1>
  <div class="row">
    <div class="col-md-4">
      <h2><strong>1</strong> <small>Flip the switch</small></h2>
      <hr>
      Select the project you want to preserve, and toggle
      the switch below to turn on automatic preservation of your software.
    </div>
    <div class="col-md-4">
      <h2><strong>2</strong> <small>Create a new version tag</small></h2>
      <hr>
      Go to GitLab and <a href="https://docs.gitlab.com/ee/workflow/releases.html">create a new version tag</a>.
      {{config.THEME_SITENAME | default('System') }} will automatically download
      a .zip-ball of each new release and register a DOI.
    </div>
    <div class="col-md-4">
      <h2><strong>3</strong> <small>Get the badge</small></h2>
      <hr>
      After your first release, a DOI badge that you can include in GitLab
      README will appear next to your project below.
    </div>
  </div>
  <div class="row">
    <div class="col-md-4" align="center">
      <br/>
      <input type="checkbox" checked data-size="large" data-animate="true" name="test-flip">
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4" align="center">
      <br>
      <a href="https://doi.org/10.14278/rodare.8475"><img src="{{ url_for('invenio_formatter_badges.badge', title='doi', value='10.14278/rodare.8475', ext='svg') }}" alt="10.14278/rodare.8475"></a><br><small class="text-muted">(example)</small>
    </div>
  </div>
</div>

{{ helpers.panel_end(with_body=False) }}
{%- if projects %}
  {%- for project_id, project in projects if project.instance and project.instance.hook %}
    {%- if loop.first %}
      {{ helpers.panel_start(_('Enabled Projects'), with_body=False) }}
    {%- endif %}
    {% include "invenio_gitlab/settings/index_item.html" with context %}
    {%- if loop.last %}
      {{ helpers.panel_end(with_body=False) }}
    {%- endif %}
  {%- endfor %}
{% endif %}


{{ helpers.panel_start(_('Projects'), with_body=False) }}
<div class="panel-body">
  <p>
    <small class="text-muted">
    Below you find a list of projects you own in GitLab. You can only preserve
    projects you are the owner of.
    </small>
  </p>
</div>
{%- if not projects %}
<div class="panel-body">
  <p>
    You have no projects on GitLab.<br>
    Go to <a href="{{config.GITLAB_BASE_URL}}/projects/new">GitLab</a> and create your first or
    click Sync-button to synchronize latest changes from GitLab.
  </p>
</div>
{%- else %}
  {%- for project_id, project in projects if not project.instance or not project.instance.hook %}
    {%- if loop.first %}
    <hr />
    {%- endif %}
    {% include "invenio_gitlab/settings/index_item.html" with context %}
  {%- endfor %}
{% endif %}
{{ helpers.panel_end(with_body=False) }}

{#- If the user has not connected his GitLab account... #}
{%- else %}
{{ helpers.panel_start(
  _('GitLab'),
  icon="fa fa-gitlab",
) }}
<div class="row" align="center">
  <h1>{{ _('Software preservation made simple!') }}</h1>
  <p class="lead">
  <a href="{{url_for('invenio_oauthclient.login', remote_app='gitlab', next=url_for('invenio_gitlab.index'))}}"
     id="connect-to-gitlab" class="btn btn-default btn-lg">
    <i class="fa fa-gitlab fa-lg"></i> {{ _('Connect') }}
  </a>
  </p>
  <p class="text-muted">
  {{ _('To get started, click "Connect" and we will get a list of your projects from GitLab.') }}
  </p>
</div>
{{ helpers.panel_end() }}
{%- endif %}
</div>
{%- endblock %}

invenio_gitlab/templates/invenio_gitlab/settings/index_item.html
{%- from "invenio_gitlab/helpers.html" import doi_badge with context -%}
{%- set doi_url = None %}
{%- set release = project.get('latest') %}
<div class="panel-body release {{release.model.status.title|lower if release.model else ''}}">
  <div class="row">
    <div class="col-md-9">
      <h4>
        <a href="{{config.GITLAB_BASE_URL}}/{{project.full_name}}" data-toggle="tooltip" title="{{ _('Go to GitLab.') }}">
          <i class="fa fa-gitlab text-muted"></i>
        </a>
        <a href="{{ url_for('.project', name=project.full_name) }}">{{ project.full_name }}</a>
      </h4>
      {%- if release.pid %}
      <p>
        {{ doi_badge(release.pid.pid_value, gitlab_id=project_id) }}
      </p>
      {%- endif %}
    </div>
    <div class="col-md-3">
      <span class="pull-right switch">
        {{helpers.repo_switch(project.instance, project_id)}}
      </span>
    </div>
  </div>
</div>
{%- if not loop.last %}
<hr />
{%- endif %}

invenio_gitlab/templates/invenio_gitlab/settings/view.html
{%- import "invenio_gitlab/settings/helpers.html" as helpers with context %}
{%- from "invenio_gitlab/helpers.html" import doi_badge with context -%}

{%- extends config.GITLAB_SETTINGS_TEMPLATE %}

{%- block css %}
{{ super() }}
{% assets "invenio_gitlab_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{%- endblock css %}

{%- block javascript %}
{{ super() }}
{% assets "invenio_gitlab_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
<script type="text/javascript">
require(['jquery', 'js/gitlab/view'], function($, view) {
  $(document).ready(function(){
    view({
      hook_url: "{{url_for('invenio_gitlab.hook')}}",
      sync_url: "{{url_for('invenio_gitlab.index')}}",
      sync_button: "button[name='sync-repos']",
      gitlab_view: ".gitlab-panels"
    });
  });
});
</script>
{%- endblock %}

{%- block settings_content %}
{%- set gitlab_rel_url = '{0}/{1}/tags/new'.format(config.GITLAB_BASE_URL, project.name) %}
{%- set latest_success_pid = None %}
{%- set latest_published = project.latest_release(status='D') %}
{%- if latest_published %}
  {%- set latest_success_pid = latest_published|release_pid %}
{%- endif %}
<div class="gitlab-panels">
  <span class="pull-right switch">
    {{helpers.repo_switch(project, project.gitlab_id, size='normal')}}
  </span>
  <h1><i class="fa fa-gitlab"></i>&nbsp;{{ project.name }}</h1>
  {%- if latest_success_pid %}
  <p>{{ doi_badge(latest_success_pid.pid_value, gitlab_id=project.gitlab_id) }}</p>
  {%- endif %}
  {{ helpers.panel_start(
    _('GitLab / Releases'),
    with_body=False,
    btn='Create release ...',
    btn_icon='fa fa-gitlab',
    btn_href=gitlab_rel_url,
  ) }}
  {%- if not releases %}
    {%- if project.enabled %}
      {%- block repo_getstarted scoped %}
      <div class="jumbotron ng-binding" align="center">
        <h1>{{_('Get started!')}}</h1>
        <p>{{_('Go to GitLab and make your first release.')}}</p>
        <h1>
          <a class="btn btn-success btn-lg" href="{{gitlab_rel_url}}">
            <i class="fa fa-gitlab"></i> {{ project.name }}
          </a>
        </h1>
      </div>
      {%- endblock repo_getstarted %}
    {%- else -%}
      {%- block repo_enable scoped %}
      <div class="jumbotron ng-binding" align="center">
        <h1>{{_('Get started!')}}</h1>
        <div class="row" align="left">
          <div class="col-md-6">
            <h2><strong>1</strong> <small>Flip the switch</small></h2>
            <hr>
            Toggle the switch below to turn on/off automatic preservation of your project.
          </div>
          <div class="col-md-6">
            <h2><strong>2</strong> <small>Create a release</small></h2>
            <hr>
            Go to GitLab and create a release. {{config.THEME_SITENAME | default('Invenio') }}
            will automatically download a .zip-ball of each new release and register a DOI.
          </div>
        </div>
        <div class="row buttons">
          <div class="col-md-6" align="center">
            {{helpers.repo_switch(project, project.gitlab_id, size='large')}}
          </div>
          <div class="col-md-6" align="center">
              <a class="btn btn-success btn-lg" href="{{gitlab_rel_url}}">
                <i class="fa fa-gitlab"></i> {{ project.name }}
              </a>
          </div>
        </div>
      </div>
      {%- endblock repo_enable %}
    {%- endif -%}
  {%- else %}
    {%- block repo_releases scoped %}
      {%- for release in releases %}
      <div class="panel-body release {{release.model.status.title|lower}}">
        {%- block release_header scoped %}
        <div class="row">
          <div class="col-md-9">
              {%- block release_title scoped %}
              <h5>
                <i class="fa fa-tag fa-fw"></i>
                <a href="#" data-toggle="collapse" data-target="#{{ release.model.id }}">
                  {{ release.model.tag }} {{ release.title }}
                </a>
              </h5>
              {%- if release.pid %}
              <p>
                <a href="https://doi.org/{{release.pid.pid_value}}" class="text-muted">
                  <i class="fa fa-fw fa-barcode"></i>
                  DOI: {{release.pid.pid_value}}
                </a>
              </p>
              {%- endif %}
              <p>
                <a href="{{'{0}/{1}/tags/{2}'.format(config.GITLAB_BASE_URL, project.name, release.model.tag)}}" class="text-muted">
                  <i class="fa fa-fw fa-gitlab"></i>
                  {{release.model.tag}}
                </a>
              </p>
              {%- endblock release_title %}
          </div>
          <div class="col-md-3">
            {%- block release_status scoped %}
            <h5>
              <i class="fa {{ release.model.status.icon }}"></i>
              <a href="#" data-toggle="collapse" data-target="#{{ release.model.id }}">
              {{release.model.status.title}}
              </a>
            </h5>
            <small class="text-muted">{{ release.model.created|naturaltime }}</small>
            {%- endblock release_status %}
          </div>
        </div>
      </div>
      {%- endblock release_header %}
      {%- block release_body scoped %}
      <div id="{{ release.model.id }}" class="panel-body release {{release.model.status.title|lower}} collapse">
        <ul class="nav nav-tabs" role="tablist">
          {%- if release.event %}
          <li class="active">
            <a href="#{{ release.model.id }}-event" data-toggle="tab">{{ _('Payload') }}</a>
          </li>
          {%- endif %}
          {%- if release.status == 'D' %}
          <li>
            <a href="#{{ release.model.id }}-metadata" data-toggle="tab">{{ _('Metadata') }}</a>
          </li>
          {%- endif %}
          {%- if release.model.errors %}
          <li>
            <a href="#{{ release.model.id }}-errors" data-toggle="tab">{{ _('Errors') }}</a>
          </li>
          {%- endif %}
        </ul>
        <div class="tab-content">
          {%- if release.event %}
          {%- block releasetab_payload scoped %}
          <div role="tabpanel" class="tab-pane active" id="{{ release.model.id }}-event">
            <small class="text-muted pull-right">{{_('Received')}} {{release.event.created|datetimeformat}}.</small>
            <h4>GitLab Payload</h4>
            <pre>{{ release.event.payload|tojson|prettyjson }}</pre>
          </div>
          {%- endblock releasetab_payload %}
          {%- endif %}
          {%- if release.status == 'D' %}
          {%- block releasetab_metadata scoped %}
          <div role="tabpanel" class="tab-pane" id="{{ release.model.id }}-metadata">
            <h4>{{_('JSON Export')}}</h4>
            <p>
            <small class="text-muted">
              {{config.THEME_SITENAME | default('Invenio')}} automatically
              extracts metadata about your repository from GitLab APIs.
              For example, the authors are determined from the
              repository's contributor statistics.
              The automatic extraction is <strong>solely a best
              guess</strong>. Add a
              <code>{{config.GITLAB_METADATA_FILE}}</code> file the root of
              your repository to explicit define the metadata. The format of
              file is the same as for our REST API (use e.g. below JSON to
              get started).
            </small>
            </p>
            <pre>{{ serializer.serialize(release.pid, release.record)|prettyjson }}</pre>
          </div>
          {%- endblock releasetab_metadata %}
          {%- endif %}
          {%- if release.model.errors %}
          {%- block releasetab_errors scoped %}
          <div role="tabpanel" class="tab-pane" id="{{ release.model.id }}-errors">
            <h4>{{ _('Errors') }}</h4>
            <pre>{{ release.model.errors|tojson|prettyjson }}</pre>
          </div>
          {%- endblock releasetab_errors %}
          {%- endif %}
        </div>
      </div>
      {%- endblock release_body %}
      {%- set is_last = loop.last %}
      {%- block release_footer scoped %}
      {%- if not is_last %}
      <hr />
      {%- endif %}
      {%- endblock release_footer %}
      {%- endfor %}
    {%- endblock repo_releases %}
  {%- endif %}
  {{ helpers.panel_end() }}
  </div>
{%- endblock %}